// Types from the SolidJS fork (github.com/kbrilla/solid, branch: stable-mutator-demo)
// These are the ACTUAL types generated by tsgo from the modified SolidJS source.
// Only stable/mutator-relevant types are included for demo clarity.
//
// Original source: packages/solid/types/src/reactive/signal.d.ts

export type Accessor<T> = stable () => T;

export type Setter<in out T> = {
  <U extends T>(...args: undefined extends T ? [] : [value: Exclude<U, Function> | ((prev: T) => U)]): undefined extends T ? undefined : U;
  <U extends T>(value: (prev: T) => U): U;
  <U extends T>(value: Exclude<U, Function>): U;
  <U extends T>(value: Exclude<U, Function> | ((prev: T) => U)): U;
};

export type Signal<T> = [get: Accessor<T>, set: mutator Setter<T> invalidates get];

export interface SignalOptions<T> extends MemoOptions<T> {
  internal?: boolean;
}

export interface BaseOptions {
  name?: string;
}

export type NoInfer<T extends any> = [T][T extends any ? 0 : never];

export type EffectFunction<Prev, Next extends Prev = Prev> = (v: Prev) => Next;

export interface EffectOptions extends BaseOptions {}

export interface MemoOptions<T> extends EffectOptions {
  equals?: false | ((prev: T, next: T) => boolean);
}

/**
 * Creates a simple reactive state with a getter and setter
 * @description https://docs.solidjs.com/reference/basic-reactivity/create-signal
 */
export declare function createSignal<T>(): Signal<T | undefined>;
export declare function createSignal<T>(value: T, options?: SignalOptions<T>): Signal<T>;

/**
 * Creates a readonly derived reactive memoized signal
 * @description https://docs.solidjs.com/reference/basic-reactivity/create-memo
 */
export declare function createMemo<Next extends Prev, Prev = Next>(fn: EffectFunction<undefined | NoInfer<Prev>, Next>): Accessor<Next>;
export declare function createMemo<Next extends Prev, Init = Next, Prev = Next>(fn: EffectFunction<Init | Prev, Next>, value: Init, options?: MemoOptions<Next>): Accessor<Next>;

/**
 * Creates a reactive effect that runs when its dependencies change
 * @description https://docs.solidjs.com/reference/basic-reactivity/create-effect
 */
export declare function createEffect<Next>(fn: EffectFunction<undefined | NoInfer<Next>, Next>): void;
export declare function createEffect<Next, Init = Next>(fn: EffectFunction<Init | Next, Next>, value: Init, options?: EffectOptions & {
  name?: string;
}): void;

/**
 * Batches multiple reactive updates
 * @description https://docs.solidjs.com/reference/reactive-utilities/batch
 */
export declare function batch<T>(fn: Accessor<T>): T;

/**
 * Reads a reactive value without tracking it
 * @description https://docs.solidjs.com/reference/reactive-utilities/untrack
 */
export declare function untrack<T>(fn: Accessor<T>): T;
